from core.topic_tree import get_sorted_main_topics, normalize_topic_tree
from core.validation import validate_report_inputs
from core.workflow import PHASE_LABELS


def _render_topic_tree(topic_tree: dict) -> list[str]:
    lines: list[str] = []
    for main_topic in get_sorted_main_topics(normalize_topic_tree(topic_tree)):
        if main_topic.get("is_other") and not main_topic.get("subtopics"):
            continue

        lines.append(f"### {main_topic['title']}")
        if main_topic.get("description"):
            lines.append(main_topic["description"])
        lines.append(
            f"- Main topic priority - company: {main_topic['priorities'].get('company', '-')}/5"
        )
        lines.append(
            f"- Main topic priority - candidate: {main_topic['priorities'].get('candidate', '-')}/5"
        )

        for subtopic in main_topic.get("subtopics", []):
            company_position = subtopic.get("positions", {}).get("company", {})
            candidate_position = subtopic.get("positions", {}).get("candidate", {})
            lines.append(f"- Subtopic: {subtopic['title']}")
            lines.append(f"  - Description: {subtopic.get('description', '-') or '-'}")
            lines.append(f"  - Created by: {subtopic.get('created_by', '-')}")
            lines.append(f"  - Phase created: {subtopic.get('phase_created', '-')}")
            lines.append(
                f"  - Company: {company_position.get('value', '-') or '-'} "
                f"(priority: {company_position.get('priority', '-')}/5, "
                f"deal breaker: {'yes' if company_position.get('deal_breaker') else 'no'})"
            )
            lines.append(
                f"  - Candidate: {candidate_position.get('value', '-') or '-'} "
                f"(priority: {candidate_position.get('priority', '-')}/5, "
                f"deal breaker: {'yes' if candidate_position.get('deal_breaker') else 'no'})"
            )
            if company_position.get("notes"):
                lines.append(f"  - Company notes: {company_position['notes']}")
            if candidate_position.get("notes"):
                lines.append(f"  - Candidate notes: {candidate_position['notes']}")
        lines.append("")

    return lines


def build_report(data: dict, results: dict) -> str:
    errors = validate_report_inputs(data, results)
    if errors:
        raise ValueError("; ".join(errors))

    company = data.get("company", {})
    candidate = data.get("candidate", {})
    session_id = data.get("session_id", "session_001")

    lines = [
        "# Negotiation Report",
        "",
        f"- Session: `{session_id}`",
        "",
        "## Negotiation subject",
        data.get("job_description", "_No content_"),
        "",
        "## Parties",
        f"- Company: **{company.get('name', '-')}**",
        f"- Candidate: **{candidate.get('name', '-')}**",
        "",
        "## Topic structure",
        "",
    ]
    lines.extend(_render_topic_tree(data.get("topic_tree", {})))

    for phase in ["ALIGNMENT", "NEGOTIATION", "CLOSING"]:
        if phase not in results:
            continue

        round_content = results[phase]
        lines.extend(
            [
                "---",
                "",
                f"## {PHASE_LABELS[phase]}",
                "",
                "### Company position",
                round_content.get("company", "_No content_"),
                "",
                "### Candidate position",
                round_content.get("candidate", "_No content_"),
                "",
                "### Summary",
                round_content.get("summary", "_No content_"),
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "## Final status",
            "Report generated by the human-in-the-loop negotiation prototype.",
        ]
    )

    return "\n".join(lines)
