from core.privacy import extract_shared_topic_tree
from core.snapshots import get_latest_round_snapshot
from core.topic_tree import get_sorted_main_topics, normalize_topic_tree
from core.validation import validate_report_inputs
from core.workflow import PHASE_LABELS


def _render_topic_tree(topic_tree: dict) -> list[str]:
    lines: list[str] = []
    for main_topic in get_sorted_main_topics(normalize_topic_tree(topic_tree)):
        if main_topic.get("is_other") and not main_topic.get("subtopics"):
            continue

        lines.append(f"### {main_topic['title']}")
        if main_topic.get("description"):
            lines.append(main_topic["description"])

        for subtopic in main_topic.get("subtopics", []):
            lines.append(f"- Subtopic: {subtopic['title']}")
            lines.append(f"  - Description: {subtopic.get('description', '-') or '-'}")
            lines.append(f"  - Created by: {subtopic.get('created_by', '-')}")
            lines.append(f"  - Phase created: {subtopic.get('phase_created', '-')}")
        lines.append("")

    return lines


def build_report(data: dict, results: dict) -> str:
    errors = validate_report_inputs(data, results)
    if errors:
        raise ValueError("; ".join(errors))

    company = data.get("company", {})
    candidate = data.get("candidate", {})
    session_id = data.get("session_id", "session_001")

    lines = [
        "# Negotiation Report",
        "",
        f"- Session: `{session_id}`",
        "",
        "## Negotiation subject",
        data.get("job_description", "_No content_"),
        "",
        "## Parties",
        f"- Company: **{company.get('name', '-')}**",
        f"- Candidate: **{candidate.get('name', '-')}**",
        "",
        "## Topic structure",
        "_Private priorities, deal breakers, and notes are intentionally excluded from this report._",
        "",
    ]
    shared_topic_tree = data.get("shared_topic_tree") or extract_shared_topic_tree(data.get("topic_tree", {}))
    lines.extend(_render_topic_tree(shared_topic_tree))

    for phase in ["ALIGNMENT", "NEGOTIATION", "CLOSING"]:
        if phase not in results:
            continue

        round_content = results[phase]
        lines.extend(
            [
                "---",
                "",
                f"## {PHASE_LABELS[phase]}",
                "",
            ]
        )
        snapshot = get_latest_round_snapshot(data, phase)
        if snapshot and snapshot.get("captured_at"):
            lines.extend(
                [
                    f"- Snapshot captured: `{snapshot['captured_at']}`",
                    "",
                ]
            )
        lines.extend(
            [
                "### Company position",
                round_content.get("company", "_No content_"),
                "",
                "### Candidate position",
                round_content.get("candidate", "_No content_"),
                "",
                "### Summary",
                round_content.get("summary", "_No content_"),
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "## Final status",
            "Report generated by the human-in-the-loop negotiation prototype.",
        ]
    )

    return "\n".join(lines)
